// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhCgaUJOSJDfx-4uNIw-BxqZkSWm0sR5o',
    appId: '1:769503847703:web:75d4b1adc8065941718352',
    messagingSenderId: '769503847703',
    projectId: 'fir-flutter-codelab-e41be',
    authDomain: 'fir-flutter-codelab-e41be.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-e41be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOgxAdJSw95xk9ZM2HWm4tqQmk-oLAjg4',
    appId: '1:769503847703:android:27aa64d18c82a1bd718352',
    messagingSenderId: '769503847703',
    projectId: 'fir-flutter-codelab-e41be',
    storageBucket: 'fir-flutter-codelab-e41be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7sRshP9Vh8qe0rSG88MSpV0jQN9AsDjI',
    appId: '1:769503847703:ios:250fe810dfc21525718352',
    messagingSenderId: '769503847703',
    projectId: 'fir-flutter-codelab-e41be',
    storageBucket: 'fir-flutter-codelab-e41be.appspot.com',
    iosClientId: '769503847703-sgotth75hig6i6eav4imqk9fgirj1ce6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7sRshP9Vh8qe0rSG88MSpV0jQN9AsDjI',
    appId: '1:769503847703:ios:250fe810dfc21525718352',
    messagingSenderId: '769503847703',
    projectId: 'fir-flutter-codelab-e41be',
    storageBucket: 'fir-flutter-codelab-e41be.appspot.com',
    iosClientId: '769503847703-sgotth75hig6i6eav4imqk9fgirj1ce6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
